[
  "bio/bio_48.md",
  "bio/bio_114.md",
  "testimonials.md",
  "way-of-working.md",
  "projects/la-casa-shambala.md",
  "projects/jewzy-tv.md",
  "projects/hsbc-global-corporate-payments.md",
  "projects/mercedes-benz.md",
  "projects/srf.md",
  "projects/barclaycard-idv.md"
]
